language: cpp
sudo: require
git:
  depth: 10
matrix:
  include:
    - os: linux
      dist: xenial
      name: Linux gcc 4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      env:
        - CC=gcc-4.8
        - CXX=g++-4.8

    - os: linux
      dist: xenial
      name: Linux gcc 9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - CC=gcc-9
        - CXX=g++-9

    - os: linux
      dist: xenial
      name: Linux clang 3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-3.6
          packages:
            - clang-3.6
            - g++-4.9
      env:
        - CC=clang-3.6
        - CXX=clang++-3.6

    - os: linux
      dist: xenial
      name: Linux clang 8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
            - g++-8
      env:
        - CC=clang-8
        - CXX=clang++-8

before_install:
  - pwd
  - pyenv global system 3.7

install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade; brew install cmake; fi
before_script:
- mkdir build
- cd build
- cmake .. -DADD_TESTS=ON -DADD_PYTHON=OFF
- make VERBOSE=1 -j2
- mkdir -p $HOME/.local/share/PROPOSAL/tables
script:
- travis_wait 60 ctest -j2 --verbose -E "(Brems|Photo|Epair|Mupair)"
after_success:
- git clean -fdx
- cd $HOME/tudo-astroparticlephysics
- tar czf PROPOSAL-$TRAVIS_BRANCH.tar.gz --exclude-vcs PROPOSAL
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: nWVAw2ifn2zkdDkeLLKgXZgWRo/A9Z6LL+0J8xCscKay6Jn4dJ01ODyT+KJGbsKXHMMvalJXDgE7A8c5x6RN+ljq+sEr9FIvxwXmV0npsZhoRBoCmQPrQ8JQO1+fyKcNv60Os9UuPBSGCwdoZ5oXkIMFRSt7CmPKagkgaom8u9Zs3rkKtXN9TUW1I5MOxrXJZPLepd1Hx8ZS7cejcZ2tyovcn56uG/LOR0RJstU1KShNIP58B4iV+jaiqEJnd0rtzDoc8LND0vdEmuVSAphb/DXOhDa0greiIOiXsVYfcfXda1vb+Uo/kafznfYs+8PnqOwQqom0oE3n6CTY+ffsvSbJrn9UQoAaHaC2XwyLSSRyy+5mJB6nhCi+oBHg+bvWnCmYf2RizuHHqpKB3c3TA9iQt1lxlrzPtxibykSXFbFRv6NjCN+wfxinFnIO2hUczPzHDmwFRLM5bzuQZ4j8Q6dV5X8UBiws0wOmkSRL0H4PB7UldqiP/qAV2XYT6V4l5cpaDlVGUOlSTheK1gejpbvJw256ggTuYo9/hBWPPwniUGXbMTeMViqSRRY3X0r9hz/zxvt7oECJGmsy2YmeLi2LnKVKaRWhsrIavlD9A167dNtrrYgflwPbVwe84lYlO2vJxTqTEygeZqMkOsT0myBYQi03xesJ3IBtiCMWgME=
  file: PROPOSAL-$TRAVIS_BRANCH.tar.gz
  on:
    repo: tudo-astroparticlephysics/PROPOSAL
    tags: true
    condition: $CXX = g++-9
